### ISSUE TITLE
Hello,Ask mysql database file there?

### ISSUE THREAD

**Issue by sonwa** [haykmuradyan/laravel-api-app#1]
Hello,Ask mysql database file there?

**Comment by haykmuradyan** [comment]
clon project
install laravel
create db (set db Name in .env).
run command php artisan migrate

.env. example here
APP_ENV=local
APP_DEBUG=true
APP_KEY=base64:U4W9JB1nUJCiFxWmWup50cJVEbO4p+W/SqzdceYO234=

DB_HOST=127.0.0.1
DB_DATABASE=db_name
DB_USERNAME=root
DB_PASSWORD=

CACHE_DRIVER=redis
SESSION_DRIVER=file
QUEUE_DRIVER=database

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=sparkpost
SPARKPOST_SECRET=
MAIL_HOST=smtp.mailgun.org
MAIL_PORT=
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=tls

MAILGUN_API_KEY=
MAIL_FROM_ADDRESS=
SUPPORT_MAIL=
MAIL_FROM_NAME=
MAILGUN_DOMAIN=
MAILGUN_SECRET=


BROADCAST_DRIVER=
PUSHER_KEY=
PUSHER_SECRET=
PUSHER_APP_ID=


BRAINTREE_ENV=
BRAINTREE_MERCHANT_ID=
BRAINTREE_PUBLIC_KEY=
BRAINTREE_PRIVATE_KEY=

FCM_PROTOCOL=http

FCM_SERVER_KEY=

QUICKBLOK_APP_ID=
QUICKBLOK_AUTH_KEY=
QUICKBLOK_AUTH_SECRET=
